home/urls.py
#from django.contrib import admin 
from django.urls import path
from . import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.intro),
]

photo_upload/urls.py
#from django.contrib import admin 
from django.urls import path
from . import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.photo_upload),
    path('download_zip/', views.download_zip_file, name="download_zip_file"),
]


'''
#The following is not necessary here, it should go to the main urls.py section
#Only for development purpose, exclude during production
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''

protein_design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from get_sequence import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    #path('learndj/', views.learn_django),
    path('home/', include('home.urls')),
    path('photo_upload/', include('photo_upload.urls')),
    path('resize_result/', include('resize_result.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resize_result/urls.py
#from django.contrib import admin 
from django.urls import path
from . import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.resize_result),
]


home/models.py
from django.db import models

# Create your models here.

photo_upload/models.py
from django.db import models

# Create your models here.





resize_result/models.py
from django.db import models

# Create your models here.

photo_upload/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator


class UploadPhotoForm(forms.Form):
    title = forms.CharField(label="Title of the image")
    img = forms.ImageField(label="Image File")
    #recipient = forms.EmailField(label="Your email (results will be sent to this email)")

    

home/views.py
from django.shortcuts import render

# Create your views here.
def intro(request):
    details={
    'title': "Protein Sequence Prediction",
    'intro': " It's a website for Protein Sequence Prediction "
    }

    return render(request, 'home/home.html', details)

photo_upload/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.files import File #I added
#from . import form
from .forms import UploadPhotoForm
from django.core.mail import send_mail #for contactForm class
from django.core.mail import EmailMessage #for sending email with attachment
from django.core.files.storage import FileSystemStorage #for storing uploaded files in media

#from .test import *
from .PhotoResize import *

#import subprocess
from subprocess import run, PIPE #For calling external python script
import sys


# Create your views here.

def photo_upload(request):
    #return HttpResponse("Hello Python!!")
    # if this is a POST request we need to process the form data
    context = {}
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = UploadPhotoForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            
            # process the data in form.cleaned_data as required
            # ...
            #1st parameter - input file
            # Uploaded file saving
            title=form.cleaned_data.get("title")

            #Deleting the all the media files before uploading:
            dir = './media/'
            for file in os.scandir(dir):
                os.remove(file.path)

            #For saving multiple files:
            for f in request.FILES.getlist("img"):
                #print(f.name)
                fs = FileSystemStorage()
                img_name = fs.save(f.name, f)
                img_path = fs.url(img_name)
                img_path = '.'+img_path
                #print(img_path)

            """ 
            #For saving single file:  
            uploaded_img=request.FILES['img']
            print(uploaded_img.name)
            fs = FileSystemStorage()
            img_name = fs.save(uploaded_img.name, uploaded_img)
            img_path = fs.url(img_name)
            img_path = '.'+img_path
            print(img_path)
            """
            #recipient = form.cleaned_data['recipient'] #for email
            main()

            return render(request, 'resize_result/resize_result.html')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = UploadPhotoForm()
    context['form']= form
    return render(request, 'photo_upload/photo_upload.html', context)

def download_zip_file(request):
    zip_file = open('./resize_result/static/resized_photos.zip', 'rb') #Here "Putting 'r' instead of 'rb' gave UnicodeDecodeError initially
    response = HttpResponse(zip_file, content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename="%s"' % 'resized_photos.zip'
    return response
    #return FileResponse(zip_file)
    

resize_result/views.py
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def resize_result(request):
    #return HttpResponse("Hello Python!!")
    return render(request, 'resize_result/resize_result.html')


templates/base.html
{% load static %}<!doctype html>
<html lang="en">
	<head>
		<meta charset = "UTF-8">
		<meta name='viewport' content="width=device-width, initial-scale=1.0" />
							<!--
							<style> body {
								background-color: slateblue;
							} </style>
							-->
		<style>
			.container {
				position: relative;
				text-align: center;
				color: Black;
			}

			.header1 {
				position:absolute;
				top:115px;
				left:196px;
			}

			.header2 {
				position:absolute;
				top:158px;
				left:200px;
			}

			.text1 {
				position:absolute;
				top:210px;
				left:202px;
			}

			.container .button {
				position: absolute;
				top: 360px;
				left: 198px;
				background-color: black;
				color: white;
				font-size: 16px;
				padding: 15px 40px;
				border: none;
				cursor: pointer;
				border-radius: 40px;
				text-align: center;
				font-family:"Montserrat";
			}

			
			.column1 {
				float: left;
				width: 50%;
				margin-left: 200px;
				/* padding-left: 200px;
				padding-top: 50px; */
			}			
			
			.column2 {
				float: right;
				width: 20%;
				margin-right: 150px;
			}

			.row:after{
				content: "";
				display: table;
				clear: both;
			}

		</style>

		<!-- <title> home </title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<link rel="stylsheet" href="{{ STATIC_URL }}style.css"> -->
		
		
	</head>
	
	<body>

		<style>
			body {
				margin: 0;
				font-family: 'Proxima Nova', 'Gill Sans', sans-serif
			}
				.topnav {
				overflow: hidden;
				background-color: #FFFFFF
			}
			.topnav a {
				float: right;
				/* margin-right:30px; */
				color: black;
				text-align: center;
				padding: 16px 15px;
				text-decoration: none;
				font-size: 16px;
			}
			.topnav a:hover {
				background-color: #E8E8E8;
				color: black;
			}
			.topnav a.active {
				background-color: #E8E8E8;
			color: black;
			}
		</style>
		
		<div class="topnav">
			<style>
			ul{
				list-style-type:none;
				margin: 0;
				padding: 0;	
			}
			li {
				display: inline;
			}
			</style>

			<ul style="margin-right:200px">
			<li style="width:100px;height:20px;background-color:#FFFFFF">&nbsp; </li>
			<li><a href="http://127.0.0.1:8000/contact/">CONTACT</a></li>
			<li><a href="http://127.0.0.1:8000/get_sequence/">UPLOAD</a></li>
			<li><a class="active" href="http://127.0.0.1:/8000/home/">HOME</a></li>
			<!-- <li	style="position:absolute;left:200px"><a href="http://127.0.0.1:8000/home/"><button class="logobutton">PROTEIN SEQUENCING</button></a></li> -->
			<li style ="font-family:'Montserrat','Proxima Nova',sans-serif;font-size:20px;float:left;margin-left:200px;margin-top:13px" ><h>PHOTO SHARE</h></li>
		  	</ul>
		</div>
		
		<div style="height:1px;background-color:#979797;"></div>	

		<div class="container">
			<div style="height:500px;background-color:#d8b2d8;"></div>
			<div class="header1"><h style="text-align:'left';font-family:'Pangram', sans-serif; font-size:40px">Photo sharing experience</h></div>
			<div class="header2"><h style="text-align:'left';font-family:'Pangram', sans-serif; font-size:40px">with Photo Resizing option!</h></div>
			<div class="text1"><h style="color:#767676;text-align:'left';letter-spacing:1px;font-family:'Proxima Nova', sans-serif; font-size:18px">a web based tool for real time protein comparison and analysis</div>
			<a href= "http://127.0.0.1:8000/get_sequence/">
				<button class = "button">TRY IT NOW</button>
			</a>

		</div>
  </body>
</html>

templates/home.html
<html lang="en">
	<head>
		<meta charset = "UTF-8">
		<meta name='viewport' content="width=device-width, initial-scale=1.0" />
							<!--
							<style> body {
								background-color: slateblue;
							} </style>
							-->
		<style>
			.container {
				position: relative;
				text-align: center;
				color: Black;
			}

			.header1 {
				position:absolute;
				top:115px;
				left:196px;
			}

			.header2 {
				position:absolute;
				top:158px;
				left:200px;
			}

			.text1 {
				position:absolute;
				top:210px;
				left:202px;
			}

			.container .button {
				position: absolute;
				top: 360px;
				left: 198px;
				background-color: black;
				color: white;
				font-size: 16px;
				padding: 15px 40px;
				border: none;
				cursor: pointer;
				border-radius: 40px;
				text-align: center;
				font-family:"Montserrat";
			}

			/* .logobutton
			{
				padding:5px 25px;
				top:2px;
				left:200px;
				background-color: white;
				cursor:pointer;
				border: none;
				font-family:'Montserrat','Proxima Nova',sans-serif;
				font-size:20px;
				float:left;
				
			} */

			.column1 {
				float: left;
				width: 50%;
				margin-left: 200px;
				/* padding-left: 200px;
				padding-top: 50px; */
			}			
			
			.column2 {
				float: right;
				width: 20%;
				margin-right: 150px;
			}

			.row:after{
				content: "";
				display: table;
				clear: both;
			}

		</style>

		<!-- <title> home </title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<link rel="stylsheet" href="{{ STATIC_URL }}style.css"> -->
		
		
	</head>
	
	<body>

		<style>
			body {
				margin: 0;
				font-family: 'Proxima Nova', 'Gill Sans', sans-serif
			}
				.topnav {
				overflow: hidden;
				background-color: #FFFFFF
			}
			.topnav a {
				float: right;
				/* margin-right:30px; */
				color: black;
				text-align: center;
				padding: 16px 15px;
				text-decoration: none;
				font-size: 16px;
			}
			.topnav a:hover {
				background-color: #E8E8E8;
				color: black;
			}
			.topnav a.active {
				background-color: #E8E8E8;
			color: black;
			}
		</style>
		
		<div class="topnav">
			<style>
			ul{
				list-style-type:none;
				margin: 0;
				padding: 0;	
			}
			li {
				display: inline;
			}
			</style>

			<ul style="margin-right:200px">
			<li style="width:100px;height:20px;background-color:#FFFFFF">&nbsp; </li>
			<li><a href="http://127.0.0.1:8000/contact/">CONTACT</a></li>
			<li><a class = "active" href="http://127.0.0.1:8000/refer_page">REFERENCES</a></li>
			<li><a href="http://127.0.0.1:8000/get_sequence/">SEARCH</a></li>
			<li><a href="http://127.0.0.1:/home/">HOME</a></li>
			<!-- <li	style="position:absolute;left:200px"><a href="http://127.0.0.1:8000/home/"><button class="logobutton">PROTEIN SEQUENCING</button></a></li> -->
			<li style ="font-family:'Montserrat','Proxima Nova',sans-serif;font-size:20px;float:left;margin-left:200px;margin-top:13px" ><h>PROTEIN SEQUENCING</h></li>
		  	</ul>
		</div>
		
		<div style="height:1px;background-color:#979797;"></div>	

		<div class="container">
			<div style="height:500px;background-color:#E2DDC0;"></div>
			<div class="header1"><h style="text-align:'left';font-family:'Pangram', sans-serif; font-size:40px">Quick and Easy Searches</h></div>
			<div class="header2"><h style="text-align:'left';font-family:'Pangram', sans-serif; font-size:40px">for 3D Protein Structure</h></div>
			<div class="text1"><h style="color:#767676;text-align:'left';letter-spacing:1px;font-family:'Proxima Nova', sans-serif; font-size:18px">a web based tool for real time protein comparison and analysis</div>
			<a href= "http://127.0.0.1:8000/get_sequence/">
				<button class = "button">TRY IT NOW</button>
			</a>

		</div>

		
		<div style="margin-top:100px" class="row">
			<div class="column1">
				<h style="font-family:'Proxima Nova', sans-serif;font-size:30px;color:#2A3FAC"><b>3D SURFER 2.0</b></h>
				<p style="line-height:24px;font-family:'Proxima Nova', sans-serif;font-size:18px;color:black">A web-based tool for real-time protein surface comparison and analysis. The server integrates a repertoire of methods to assist in high throughput screening and visualization of protein surface comparisons. 3D-Zernike Descriptors (3DZD) are utilized for the efficient comparison between a protein surface of a single chain, a single domain, or a single complex against all protein structures in the latest Protein Data Bank (PDB). Conveniently, the web interface also renders animated protein rotations, displays CATH protein structure classification codes, and structure alignment calculations using the Combinatorial Extension (CE) algorithm, and identifies geometric (i.e., pocket) regions on a given structure.</p>
			</div>
			<div class="column2">
				<h style="font-family:'Proxima Nova', sans-serif;font-size:24px;color:#2A3FAC"><b>LATEST UPDATES</b></h>
				<p style="height:1200px;width:250px;line-height:22px;font-family:'Proxima Nova', sans-serif;font-size:16px;color:black"><b>Surface representation:</b> Two options of surface representation are provided. The first one is the all-atom-surface representation, and the second is the backbone-atom-surface representation, which includes alpha C (CA), C, and N atoms in the main chain.
					<br><br><b>Database:</b> 3DZD of protein chains, domains, complexes and a combination of three above are repertoried in the website.Batch mode: A batch mode is available to run multiple proteins for uses who would like to benchmark their methods against our approach.
					<br><br><b>Maintenance:</b> The databases are weekly updated in pace with the latest PDB.</p>
			</div>
		</div>



	</body>
</html>

						
						
						






templates/home/home.html
<html lang="en">
	<head>
		<meta charset = "UTF-8">
		<meta name='viewport' content="width=device-width, initial-scale=1.0" />
							<!--
							<style> body {
								background-color: slateblue;
							} </style>
							-->
		<style>
			.container {
				position: relative;
				text-align: center;
				color: Black;
			}

			.header1 {
				position:absolute;
				top:115px;
				left:196px;
			}

			.header2 {
				position:absolute;
				top:158px;
				left:200px;
			}

			.text1 {
				position:absolute;
				top:210px;
				left:202px;
			}

			.container .button {
				position: absolute;
				top: 360px;
				left: 198px;
				background-color: black;
				color: white;
				font-size: 16px;
				padding: 15px 40px;
				border: none;
				cursor: pointer;
				border-radius: 40px;
				text-align: center;
				font-family:"Montserrat";
			}

			
			.column1 {
				float: left;
				width: 50%;
				margin-left: 200px;
				/* padding-left: 200px;
				padding-top: 50px; */
			}			
			
			.column2 {
				float: right;
				width: 20%;
				margin-right: 150px;
			}

			.row:after{
				content: "";
				display: table;
				clear: both;
			}

		</style>

		<!-- <title> home </title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<link rel="stylsheet" href="{{ STATIC_URL }}style.css"> -->
		
		
	</head>
	
	<body>

		<style>
			body {
				margin: 0;
				font-family: 'Proxima Nova', 'Gill Sans', sans-serif
			}
				.topnav {
				overflow: hidden;
				background-color: #FFFFFF
			}
			.topnav a {
				float: right;
				/* margin-right:30px; */
				color: black;
				text-align: center;
				padding: 16px 15px;
				text-decoration: none;
				font-size: 16px;
			}
			.topnav a:hover {
				background-color: #E8E8E8;
				color: black;
			}
			.topnav a.active {
				background-color: #E8E8E8;
			color: black;
			}
		</style>
		
		<div class="topnav">
			<style>
			ul{
				list-style-type:none;
				margin: 0;
				padding: 0;	
			}
			li {
				display: inline;
			}
			</style>

			<ul style="margin-right:200px">
			<li style="width:100px;height:20px;background-color:#FFFFFF">&nbsp; </li>
			<li><a href="http://127.0.0.1:8000/photo_upload/">UPLOAD</a></li>
			<li><a class="active" href="http://127.0.0.1:/8000/home/">HOME</a></li>
			<!-- <li	style="position:absolute;left:200px"><a href="http://127.0.0.1:8000/home/"><button class="logobutton">PROTEIN SEQUENCING</button></a></li> -->
			<li style ="font-family:'Montserrat','Proxima Nova',sans-serif;font-size:20px;float:left;margin-left:200px;margin-top:13px" ><h>RESIZE PHOTO</h></li>
		  	</ul>
		</div>
		
		<div style="height:5px;background-color:#979797;"></div>	

		<div class="container">
			<div style="height:500px;background-color:#d8b2d8;"></div>
			<div class="header1"><h style="text-align:'left';font-family:'Pangram', sans-serif; font-size:40px">RESIZE YOUR PHOTOS</h></div>
			<div class="header2"><h style="text-align:'left';font-family:'Pangram', sans-serif; font-size:40px"></h>A quick and fast experience!</div>
			<a href= "http://127.0.0.1:8000/photo_upload/">
				<button class = "button">TRY IT NOW</button>
			</a>

		</div>

		
		<div style="margin-top:100px" class="row">
			<div class="column1">
				<h style="font-family:'Proxima Nova', sans-serif;font-size:30px;color:#2A3FAC"><b>3D SURFER 2.0</b></h>
				<p style="line-height:24px;font-family:'Proxima Nova', sans-serif;font-size:18px;color:black">A web-based tool for real-time protein surface comparison and analysis. The server integrates a repertoire of methods to assist in high throughput screening and visualization of protein surface comparisons. 3D-Zernike Descriptors (3DZD) are utilized for the efficient comparison between a protein surface of a single chain, a single domain, or a single complex against all protein structures in the latest Protein Data Bank (PDB). Conveniently, the web interface also renders animated protein rotations, displays CATH protein structure classification codes, and structure alignment calculations using the Combinatorial Extension (CE) algorithm, and identifies geometric (i.e., pocket) regions on a given structure.</p>
			</div>
			<div class="column2">
				<h style="font-family:'Proxima Nova', sans-serif;font-size:24px;color:#2A3FAC"><b>LATEST UPDATES</b></h>
				<p style="height:1200px;width:250px;line-height:22px;font-family:'Proxima Nova', sans-serif;font-size:16px;color:black"><b>Surface representation:</b> Two options of surface representation are provided. The first one is the all-atom-surface representation, and the second is the backbone-atom-surface representation, which includes alpha C (CA), C, and N atoms in the main chain.
					<br><br><b>Database:</b> 3DZD of protein chains, domains, complexes and a combination of three above are repertoried in the website.Batch mode: A batch mode is available to run multiple proteins for uses who would like to benchmark their methods against our approach.
					<br><br><b>Maintenance:</b> The databases are weekly updated in pace with the latest PDB.</p>
			</div>
		</div>



	</body>
</html>

						
						
						






templates/photo_upload/photo_upload.html
<!DOCTYPE html>
<html>
    <head>
		<meta charset = "UTF-8">
		<meta name='viewport' content="width=device-width, initial-scale=1.0" />
		<title> Photo Upload </title>
	
	</head>

    <body style=background-color:#F9F8F5;>
        <style>
			body {
				margin: 0;
				font-family: 'Proxima Nova', 'Gill Sans', sans-serif
			}
				.topnav {
				overflow: hidden;
				background-color: #FFFFFF
			}
			.topnav a {
				float: right;
				/* margin-right:30px; */
				color: black;
				text-align: center;
				padding: 16px 15px;
				text-decoration: none;
				font-size: 16px;
			}
			.topnav a:hover {
				background-color: #E8E8E8;
				color: black;
			}
			.topnav a.active {
				background-color: #E8E8E8;
			color: black;
            }

            .dropzone {
                width:800px;
                height:300px;
                border:4px dashed #ccc;
                color:darkslategray;
                line-height:300px;
                text-align:center;
                border-radius:10px;
                position:absolute;
                margin-left:10%;
                margin-top:20px;
            }

            .dropzone.dragover {
                border-color:#000;
                color:#000;
            }
			
		</style>
		
		<div class="topnav">
			<style>
			ul{
				list-style-type:none;
				margin: 0;
				padding: 0;	
			}
			li {
				display: inline;
			}
			</style>

			<ul style="margin-right:200px">
			<li style="width:100px;height:20px;background-color:#FFFFFF">&nbsp; </li>
			<li><a href="http://127.0.0.1:8000/contact/">CONTACT</a></li>
			<li><a class="active"   href="http://127.0.0.1:8000/photo_upload/">UPLOAD</a></li>
			<li><a href="http://127.0.0.1:8000/home/">HOME</a></li>
			<!-- <li	style="position:absolute;left:200px"><a href="http://127.0.0.1:8000/home/"><button class="logobutton">PROTEIN SEQUENCING</button></a></li> -->
			<li style ="font-family:'Montserrat','Proxima Nova',sans-serif;font-size:20px;float:left;margin-left:200px;margin-top:13px" ><h>RESIZE PHOTO</h></li>
		  	</ul>
		</div>
		
		<div style="height:1px;background-color:#979797;"></div>

        <div style=float:left;margin-left:200px;margin-top:50px;> 
        <h1 style=margin-bottom:60px>Photo Upload </h1>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <div>
                <p>
                    {{form.title.label_tag}}
                    {{form.title}}
                </p>
            </div>            
            <br>
            <div>
                <p>
                    {{form.img.label_tag}}
                    <!--{{form.img}}-->
					<input type="file" multiple name="img" accept="image/*" required id="id_img">
                </p>
            </div>
            <br>
            <!-- {{ form.as_p }} -->
            <input type="submit" value="Submit">
        </form>
       </div>
    </body>
</html>

templates/resize_result/resize_result.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
	<head>
		<meta charset = "UTF-8">
		<meta name='viewport' content="width=device-width, initial-scale=1.0" />
		<!--
		<style> body {
			background-color: slateblue;
		} </style>
		-->
		<!-- Style to create button -->
		<style> 
			.GFG { 
				background-color: white; 
				border: 2px solid black; 
				color: green; 
				padding: 5px 10px; 
				text-align: center; 
				display: inline-block; 
				font-size: 20px; 
				margin: 10px 30px; 
				cursor: pointer; 
				text-decoration:none; 
			} 
        /* } */
    	</style> 
		<title> result </title>
	
	</head>


	<body>
		<h1>Your Resized Photos </h1>
		<a href="{% url 'download_zip_file' %}" class="GFG">
        		Download the resized photos
		</a>
	</body>

</html>